'use strict';
const $=id=>document.getElementById(id), B=Brake;
let KEY='press-brake-library-v1', profileKey='press-brake-settings-v1';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let db=B.defaults(), storageError='';
try{const saved=localStorage.getItem(KEY);if(saved)db=B.validateLibrary(JSON.parse(saved));}catch(e){storageError='Saved library could not load: '+e.message;}
let page='Run', socket, client=-1, status=null, cfg={...B.settings}, lastRx=0, compatible=false, simulation=false;
let selected=db.bends[0]?.id||null, editId=null, prepared=null, phaseIndex=0, cycle=false, gestureReady=false;
let commandId=Date.now()%1000000000, gate=new B.MoveGate(), held=new Set(), motionGesture=null, jogKey=null, eventLog=[];
let manualUnit='mm', manualMode='speed', manualSpeed='0.5', manualDistance='0.1';
const names=['Run','Create Bend','Punch/Die & Materials','Back Gauge','Manual Mode','Settings'];
function say(message,error=false){$('notice').textContent=message;$('notice').classList.toggle('error',error);eventLog.unshift(new Date().toLocaleTimeString()+' '+message);eventLog=eventLog.slice(0,40);}
function save(){B.validateLibrary(db);try{localStorage.setItem(KEY,JSON.stringify(db));}catch{throw Error('Browser storage could not save. Export a backup before closing.');}}
function send(command){if(socket?.readyState!==1)throw Error('Controller disconnected.');socket.send(command);}
function fresh(){return compatible&&status&&socket?.readyState===1&&Date.now()-lastRx<1500;}
function mine(){return fresh()&&status.enabled&&status.fault==='none'&&status.owner===client;}
function idle(){return mine()&&status.axis===-1&&!gate.pending;}
function attempt(fn){try{fn();}catch(e){say(e.message,true);}}
function cancel(message='Stopped. Prepare a move to continue.',disable=false){gate.cancel();prepared=null;cycle=false;phaseIndex=0;gestureReady=false;motionGesture=null;jogKey=null;held.clear();if(socket?.readyState===1){socket.send('stop');if(disable&&status?.owner===client)socket.send('disable');}if(message)say(message);renderLive();}
function field(id,label,value,type='number',options=''){return `<label class="field">${esc(label)}<input id="${id}" type="${type}" value="${esc(value)}" ${type==='number'?'step="any"':''} ${options}></label>`;}
function settingField(k,label,unit,min,max){if(k==='microsteps')return `<label class="field">Microstepping<select id="cfg_microsteps">${[1,2,4,8,16,32,64,128,256].map(n=>`<option value="${n}" ${cfg.microsteps===n?'selected':''}>${n}× · ${25*n} steps/mm</option>`).join('')}</select></label>`;return field('cfg_'+k,label+(unit?' ('+unit+')':''),cfg[k],'number',`min="${min}" max="${max}"`);}
function check(id,label,value=false){return `<label class="check"><input type="checkbox" id="${id}" ${value?'checked':''}>${esc(label)}</label>`;}
function val(id){return $(id).value;}function num(id){return B.numeric(val(id),$(id).parentElement.textContent.trim(),0,1e6);}
function manualNumber(id){return B.numeric(val(id),$(id).parentElement.textContent.trim(),-1000,1000);}
function intro(title,text,tag=''){return `<div class="intro"><div><h1>${title}</h1><p class="muted">${text}</p></div>${tag?`<span class="tag">${tag}</span>`:''}</div>`;}
function button(id,text,cls=''){return `<button id="${id}" class="${cls}">${text}</button>`;}
function bind(id,fn){$(id)?.addEventListener('click',()=>attempt(fn));}
function setStorageMode(isSimulation){
  const key='press-brake-library-v1'+(isSimulation?'-simulation':'');
  profileKey='press-brake-settings-v1'+(isSimulation?'-simulation':'');
  if(KEY===key)return;
  KEY=key;db=B.defaults();
  try{const saved=localStorage.getItem(KEY);if(saved)db=B.validateLibrary(JSON.parse(saved));}catch(e){say('Library could not load: '+e.message,true);}
  selected=db.bends[0]?.id||null;editId=null;
}
function currentBend(){return db.bends.find(b=>b.id===selected);}
function stepsPerMm(){return B.stepsPerMm(cfg);}
function render(){
  $('tabs').innerHTML=names.map(n=>`<button class="${n===page?'active':''}" data-page="${esc(n)}">${esc(n)}</button>`).join('');
  for(const btn of $('tabs').children)btn.onclick=()=>{cancel('',false);page=btn.dataset.page;render();};
  ({'Run':runPage,'Create Bend':bendPage,'Punch/Die & Materials':toolsPage,'Back Gauge':gaugePage,'Manual Mode':manualPage,'Settings':settingsPage})[page]();renderLive();
}
function runPage(){
  const b=currentBend();
  $('page').innerHTML=intro('Run a bend','One calibrated bend, one deliberate phase at a time.','SINGLE BEND')+`<div class="card"><h2>Saved bends</h2>${db.bends.length?db.bends.map(x=>`<div class="saved-row ${selected===x.id?'selected':''}"><div><strong>${esc(x.name)}</strong><small>${esc(x.angle)}° included · ${esc(x.width)} mm width · ${esc(db.material.name)}</small></div><button data-select="${esc(x.id)}">Select</button></div>`).join(''):'<p class="muted">Start in Punch/Die & Materials, then create your first bend.</p>'}<div class="actions">${button('newBend','+ Create bend')}${button('editBend','Edit selected','subtle')}${button('duplicateBend','Duplicate','subtle')}</div></div><div class="card"><h2>${esc(b?.name||'No bend selected')}</h2><div class="phase-strip" id="phaseStrip">${['Gauge','Approach','Clamp','Bend','Retract'].map(x=>`<span>${x}</span>`).join('')}</div><div class="grid">${['approach','clamp','final','retract'].map(k=>`<div class="muted">${k.toUpperCase()}<div class="big-coordinate">${b?esc(b[k]):'—'} <small>mm</small></div></div>`).join('')}</div><p class="muted">Manual-depth calibration. Angle and width describe your recipe; they do not automatically calculate penetration. Clamp completion is a position, not measured grip.</p><div class="actions">${button('prepareBend','Prepare single bend','primary')}${button('cancelRun','Cancel','subtle')}</div></div>`;
  for(const btn of document.querySelectorAll('[data-select]'))btn.onclick=()=>{cancel('');selected=btn.dataset.select;render();};
  bind('newBend',()=>{editId=null;page='Create Bend';render();});
  bind('editBend',()=>{if(!b)throw Error('Select a bend.');editId=b.id;page='Create Bend';render();});
  bind('duplicateBend',()=>{if(!b)throw Error('Select a bend.');const copy={...b,id:String(Date.now()),name:b.name+' copy',calibrated:false};db.bends.push(copy);save();selected=editId=copy.id;page='Create Bend';render();});
  bind('prepareBend',()=>{if(!idle())throw Error('Connect, Arm and stop before preparing.');const moves=B.plan(b,db,cfg,status);prepare(moves,true);});bind('cancelRun',()=>cancel());
}
function bendPage(){
  const b=db.bends.find(x=>x.id===editId)||{name:'Aluminum flashing bend',width:20,angle:90,approach:0,clamp:0,final:0,retract:0,x:0,useX:false,calibrated:false,notes:''};
  $('page').innerHTML=intro('Create bend','Save a repeatable recipe using depths you have physically checked.','MANUAL DEPTH')+`<div class="card"><div class="grid">${field('bendName','Bend name',b.name,'text')}${field('bendAngle','Desired included angle (°)',b.angle)}${field('bendWidth','Bend width along tooling (mm)',b.width)}<div><label class="field">Installed setup</label><p>${esc(db.tools.punch.name)} / ${esc(db.tools.die.name)}<br><small>${esc(db.material.name)}</small></p></div></div><div class="banner">Y = 0 at the upper punch home; downward positions are negative. Enter taught coordinates.</div><div class="grid" style="margin-top:20px">${['approach','clamp','final','retract'].map(k=>`<div>${field('bend_'+k,k[0].toUpperCase()+k.slice(1)+' Y (mm)',b[k])}<button data-teach="${k}" class="subtle">Use current Y</button></div>`).join('')}</div>${check('bendUseX','Position backgauge before approach',b.useX)}${field('bendX','Backgauge X from retracted home, toward die (mm)',b.x)}${check('bendCalibrated','I checked these depths for this tooling, material and desired angle.',b.calibrated)}<label class="field">Calibration / setup notes<textarea id="bendNotes">${esc(b.notes)}</textarea></label><div class="actions">${button('saveBend','Save bend & load into Run','primary')}${button('removeBend','Delete bend','danger')}</div></div>`;
  for(const btn of document.querySelectorAll('[data-teach]'))btn.onclick=()=>attempt(()=>{if(!idle()||!status.zeroed[0])throw Error('Home Y and stop before teaching.');$('bend_'+btn.dataset.teach).value=(status.position[0]/stepsPerMm()).toFixed(3);$('bendCalibrated').checked=false;});
  for(const id of ['bendAngle','bendWidth','bend_approach','bend_clamp','bend_final','bend_retract'])$(id).addEventListener('input',()=>{$('bendCalibrated').checked=false;});
  bind('saveBend',()=>{cancel('');const name=val('bendName').trim();if(!name)throw Error('Enter a name.');const record={id:editId||String(Date.now()),name,angle:num('bendAngle'),width:num('bendWidth'),useX:$('bendUseX').checked,x:num('bendX'),calibrated:$('bendCalibrated').checked,notes:val('bendNotes'),setup:B.signature(db)};for(const k of ['approach','clamp','final','retract'])record[k]=B.numeric(val('bend_'+k),k,-25,0);if(record.angle<1||record.angle>179)throw Error('Included angle must be 1–179°.');const i=db.bends.findIndex(x=>x.id===record.id);if(i<0)db.bends.push(record);else db.bends[i]=record;save();selected=record.id;page='Run';render();say('Bend saved. Prepare validates depths, homes, tooling and travel before any motion.');});
  bind('removeBend',()=>{if(!editId)return;db.bends=db.bends.filter(x=>x.id!==editId);save();editId=null;selected=db.bends[0]?.id;page='Run';render();});
}
function toolsPage(){
  $('page').innerHTML=intro('Punch / Die & Materials','Record the tooling and material values used on this machine.')+`<div class="grid three"><div class="card library punch"><h2>Punch</h2>${field('p_name','Punch',db.tools.punch.name,'text')}${field('p_height','Punch height (mm)',db.tools.punch.height)}</div><div class="card library die"><h2>Die</h2>${field('d_name','Die',db.tools.die.name,'text')}${field('d_height','Die height (mm)',db.tools.die.height)}${field('d_opening','V-die opening (mm)',db.tools.die.opening)}</div><div class="card library material"><h2>Materials</h2>${field('m_name','Material',db.material.name,'text')}${field('m_tensile','Material tensile strength (PSI)',db.material.tensile??45000)}${field('m_radiusPercent','Inside bend radius percentage (%)',db.material.radiusPercent??15)}${field('m_springback','Material springback (°)',db.material.springback)}</div></div><div class="card" style="margin-top:16px"><h2>Installed setup travel limit</h2>${field('toolDepth','Deepest permitted Y from home (mm)',db.tools.maxDepth)}<p class="muted">Choose a measured clearance limit above punch/die collision. A value of 0 blocks programmed downward travel until calibrated. Current machine Y range: −${(cfg.vMax/stepsPerMm()).toFixed(3)} to 0 mm.</p><div class="actions">${button('saveTools','Save setup','primary')}${button('applyToolLimit','Apply saved depth limit to controller')}</div><p class="muted">Applying requires disabled outputs, then Arm and home again. Tooling or material edits require reviewing affected bends.</p></div>`;
  bind('saveTools',()=>{cancel('');const copy=JSON.parse(JSON.stringify(db));copy.tools.punch={name:val('p_name').trim(),height:num('p_height')};copy.tools.die={name:val('d_name').trim(),height:num('d_height'),opening:num('d_opening')};copy.material={name:val('m_name').trim(),tensile:num('m_tensile'),radiusPercent:num('m_radiusPercent'),springback:num('m_springback')};copy.tools.maxDepth=num('toolDepth');B.validateLibrary(copy);db=copy;save();say('Tooling and material saved locally. Apply the saved depth limit before running.');});
  bind('applyToolLimit',()=>apply({...cfg,toolMax:B.pulses(db.tools.maxDepth,cfg)}));
}
function switchHomeEnabled(axis){return axis==='v'?cfg.vLimitHoming:cfg.hLimitHoming;}
function homeCard(axis){const label=axis==='v'?'Y · Punch':'X · Backgauge',sw=switchHomeEnabled(axis);return `<div class="card"><h2>${label} home</h2><p class="muted">${sw?`Switch homing: seek toward the ${axis==='v'?'upper punch':'retracted gauge'} switches, then back off. Hold Shift + ${axis==='v'?'U':'B'}.`:'Jog to the chosen reference, stop, then declare that physical location home.'}</p><div class="actions">${button('zero_'+axis,`Set ${axis==='v'?'punch':'backgauge'} manual home`)}${sw?button('home_'+axis,'Prepare switch home'):''}${button('return_'+axis,'Prepare return to home')}</div></div>`;}
function bindHomes(axis){bind('zero_'+axis,()=>{if(!idle())throw Error('Arm and stop before setting home.');if(switchHomeEnabled(axis))throw Error('Disable this axis’s switch homing in Settings to set a manual home.');cancel('');send('zero:'+axis);});bind('home_'+axis,()=>{if(!switchHomeEnabled(axis))throw Error('Switch homing is off for this axis.');if(!idle())throw Error('Arm and stop first.');prepare([{phase:'Switch home '+axis.toUpperCase(),axis,target:null,op:'home',gesture:axis==='v'?'up':'back'}]);});bind('return_'+axis,()=>manualTarget(axis,0,'Return to home'));}
function manualMove(axis,mm,label){if(!idle())throw Error('Arm and stop first.');const i=axis==='v'?0:1;if(!status.zeroed[i])throw Error('Set this axis home first for an absolute target.');const target=B.pulses(mm,cfg),amount=target-status.position[i];if(Math.abs(amount)>cfg.maxTravel)throw Error('Move exceeds the per-command budget.');return {phase:label,axis,target,amount,op:'manual',gesture:i===0?(amount<0?'down':'up'):(amount<0?'back':'forward')};}
function manualTarget(axis,mm,label){prepare([manualMove(axis,mm,label)]);}
function gaugePage(){$('page').innerHTML=intro('Back gauge','X only · both horizontal motors share STEP.','POSITIVE = TOWARD DIE')+homeCard('h')+'<div class="card"><h2>Move the backgauge</h2><p class="muted">Use Manual Mode: hold Shift + F toward the die or Shift + B away. Select continuous speed or a set distance there.</p></div><p class="muted">No motorized R axis. Current X is measured in commanded steps from the retracted reference, not flange length.</p>';bindHomes('h');}
function manualPage(){
  $('page').innerHTML=intro('Manual mode','Hold Shift with a direction key. Releasing either key stops motion.','Y DOWN = NEGATIVE')+`<div class="card manual-setup"><div class="manual-settings"><label class="field">Motion mode<select id="manualMode"><option value="speed" ${manualMode==='speed'?'selected':''}>Continuous speed</option><option value="distance" ${manualMode==='distance'?'selected':''}>Set distance per hold</option></select></label><label class="field">Units<select id="manualUnit"><option value="mm" ${manualUnit==='mm'?'selected':''}>mm</option><option value="steps" ${manualUnit==='steps'?'selected':''}>steps</option></select></label><label class="field" id="manualValueLabel">${manualMode==='speed'?'Speed':'Distance'} (${manualUnit==='mm'?(manualMode==='speed'?'mm/s':'mm'):(manualMode==='speed'?'steps/s':'steps')})<input id="manualValue" type="number" step="any" min="0" value="${esc(manualMode==='speed'?manualSpeed:manualDistance)}"></label></div><p class="muted">The setting applies to both axes. In distance mode, motion stops at the entered distance or when you release the keys. Maximum speed follows each axis limit in Settings.</p></div><div class="manual-halves"><section class="card manual-axis"><div class="manual-axis-heading"><div><span class="tag">Y AXIS</span><h2>Punch</h2></div><span class="manual-position" id="manualYPosition">— mm</span></div><p class="muted">Zero is at the upper limit switches. Down is negative.</p>${switchHomeEnabled('v')?button('home_v','Prepare punch switch home','subtle'):button('zero_v','Set punch manual home','subtle')}<div class="direction-guide"><div><span class="direction-arrow">↑</span><strong>UP</strong><kbd>Shift + U</kbd></div><div><span class="direction-arrow">↓</span><strong>DOWN</strong><kbd>Shift + D</kbd></div></div></section><section class="card manual-axis"><div class="manual-axis-heading"><div><span class="tag">X AXIS</span><h2>Backgauge</h2></div><span class="manual-position" id="manualXPosition">— mm</span></div><p class="muted">Forward moves toward the die. Back moves away.</p>${switchHomeEnabled('h')?button('home_h','Prepare backgauge switch home','subtle'):button('zero_h','Set backgauge manual home','subtle')}<div class="direction-guide"><div><span class="direction-arrow">→</span><strong>FORWARD</strong><kbd>Shift + F</kbd></div><div><span class="direction-arrow">←</span><strong>BACK</strong><kbd>Shift + B</kbd></div></div></section></div>`;
  bindHomes('v');bindHomes('h');
  $('manualMode').onchange=()=>{manualMode=val('manualMode');render();};$('manualUnit').onchange=()=>{manualUnit=val('manualUnit');render();};
  $('manualValue').oninput=()=>{if(manualMode==='speed')manualSpeed=val('manualValue');else manualDistance=val('manualValue');};gestureReady=held.size===0;
}
function settingsPage(){
  $('page').innerHTML=intro('Settings','Controller configuration is applied while disabled; homes must then be re-established.')+`<div class="card"><h2>Homing & optional sensing</h2>${check('vLimitHoming','Use the two punch limit switches for Y homing',cfg.vLimitHoming)}${check('hLimitHoming','Use the backgauge limit switch for X homing',cfg.hLimitHoming)}<p class="muted">Your current setup can use Y switch homing while X remains manual. GPIO34/35 home the two punch sides independently; GPIO36 is only used when X switch homing is enabled. NC wiring with external pull-ups: 0 = closed, 1 = open/tripped.</p>${check('stopDiag','Stop on DIAG / StallGuard (only when wired and tested)',cfg.stopDiag)}<p class="muted">UART driver protection remains active when DIAG stopping is off.</p><p id="limitStatus" class="banner"></p></div><details class="card" open><summary>Advanced · Motion configuration & diagnostics</summary><p class="muted">Microstepping changes commanded steps per millimeter (25 × the selected value). Pulse based speed, acceleration, travel, backoff and budget settings remain in steps and may need adjustment after a change. Applying settings clears both homes.</p><div class="grid">${B.fields.map(args=>settingField(...args)).join('')}</div><div class="actions">${button('applySettings','Apply settings / clear fault','primary')}${button('exportApplied','Print applied settings in Start UI window')}</div><p class="muted">Settings are RAM-only on the ESP. A copy is stored in this browser after a successful apply; restoring it never arms or homes automatically.</p>${button('restoreProfile','Load saved settings into form','subtle')}<details><summary>Driver telemetry</summary><pre id="diagnostics"></pre></details><details><summary>Recent notices</summary><pre id="events">${esc(eventLog.join('\n'))}</pre></details></details><div class="card"><h2>Library backup</h2><div class="actions">${button('exportLibrary','Export tooling & bends')}<label class="field">Import library<input id="importLibrary" type="file" accept="application/json,.json"></label></div><p class="muted">Import replaces this browser's library. Keep an exported backup. Saved jobs and controller settings are separate.</p></div><div class="card"><h2>Connection</h2><p class="muted">UI stays on this computer. WebSocket commands pass through the local Node server. The PC server uses the ESP USB programming cable. Close Arduino Serial Monitor before starting the UI. Select the COM port in Start UI.cmd; unplugging the cable stops motion and requires Arm and home again.</p>${simulation?button('sample','Load simulation example','subtle'):''}</div>`;
  bind('applySettings',()=>{const next={};for(const [k]of B.fields)next[k]=num('cfg_'+k);next.stopDiag=$('stopDiag').checked;next.vLimitHoming=$('vLimitHoming').checked;next.hLimitHoming=$('hLimitHoming').checked;apply(next);});
  bind('restoreProfile',()=>{const p=JSON.parse(localStorage.getItem(profileKey)||'null');B.validateSettings(p);for(const [k]of B.fields)$('cfg_'+k).value=p[k];$('stopDiag').checked=p.stopDiag;$('vLimitHoming').checked=p.vLimitHoming;$('hLimitHoming').checked=p.hLimitHoming;say('Profile loaded into form only. Inspect it, then Apply while disabled.');});
  bind('exportApplied',()=>send('export'));bind('exportLibrary',()=>{const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='press-brake-library.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
  $('importLibrary').onchange=async e=>{try{cancel('');const f=e.target.files[0];if(!f)return;if(f.size>100000)throw Error('Library is too large.');db=B.validateLibrary(JSON.parse(await f.text()));save();selected=db.bends[0]?.id;render();say('Library imported. Review tooling and apply the controller limit before running.');}catch(err){say(err.message,true);}};
  bind('sample',()=>{if(!simulation)throw Error('Simulation only.');db=B.defaults();Object.assign(db.tools.punch,{name:'DEMO punch',height:20});Object.assign(db.tools.die,{name:'DEMO V die',height:10,opening:8});db.tools.maxDepth=10;db.bends=[{id:'demo',name:'DEMO bend',width:25,angle:90,approach:-2,clamp:-3,final:-3.3,retract:-2,x:5,useX:true,calibrated:true,notes:'Simulation example only. Never reuse these positions on hardware.',setup:B.signature(db)}];selected='demo';say('Simulation example loaded in memory only. Apply 10 mm tool limit, Arm, and set both homes.');page='Run';render();});
}
async function apply(next){try{if(!fresh()||status.enabled)throw Error('Connect and Disable drivers before applying.');const changedMicrosteps=next.microsteps!==cfg.microsteps;if(changedMicrosteps)next.toolMax=0;B.validateSettings(next);const data=new URLSearchParams;for(const [k,v]of Object.entries(next))data.set(k,typeof v==='boolean'?(v?'1':'0'):String(v));const res=await fetch('/settings',{method:'POST',body:data});const text=await res.text();if(!res.ok)throw Error(text);cfg={...next};try{localStorage.setItem(profileKey,JSON.stringify(cfg));}catch{}say(text+(changedMicrosteps?' Reapply the saved tool depth limit at the new step scale.':''));render();}catch(e){say(e.message,true);}}
function prepare(moves,isCycle=false){if(!idle())throw Error('Arm and stop first.');gate.cancel();prepared=JSON.parse(JSON.stringify(moves));phaseIndex=0;cycle=isCycle;gestureReady=held.size===0;motionGesture=null;say('Prepared. '+(gestureReady?'Hold the indicated controls to start.':'Release all keys, then hold the indicated controls.'));renderLive();}
function gestureDown(kind){const key={down:'KeyD',up:'KeyU',forward:'KeyF',back:'KeyB'}[kind];return Boolean(key&&held.has(key)&&(held.has('ShiftLeft')||held.has('ShiftRight')));}
function executePrepared(){if(!prepared||gate.pending||!gestureReady)return;if(!idle())throw Error('Motion is not available.');const m=prepared[phaseIndex];if(!gestureDown(m.gesture))return;const id=++commandId;gate.begin(id,m.axis==='v'?0:1,m.target);gestureReady=false;motionGesture=m.gesture;const command=m.op==='home'?'home:'+m.axis:m.op==='manual'?`manual:${m.axis}:${m.amount}`:m.op==='step'?`step:${m.axis}:${m.amount}`:`goto:${m.axis}:${m.target}`;send(id+'|'+command);renderLive();}
function complete(){motionGesture=null;if(jogKey){jogKey=null;say('Jog reached its travel boundary or command budget. Release keys before another jog.');gestureReady=false;renderLive();return;}phaseIndex++;if(phaseIndex>=prepared.length){prepared=null;cycle=false;say('Complete. Motion stopped; motors remain armed.');}else say('Phase complete. Release controls, then hold for '+prepared[phaseIndex].phase+'.');gestureReady=false;renderLive();}
const jogs={KeyU:['v','+'],KeyD:['v','-'],KeyF:['h','+'],KeyB:['h','-']};
function jogHeld(key){return Boolean(held.has(key)&&(held.has('ShiftLeft')||held.has('ShiftRight')));}
function startJog(){if(page!=='Manual Mode'||prepared||gate.pending||jogKey||!gestureReady)return;const key=Object.keys(jogs).find(jogHeld);if(!key)return;if(!idle())throw Error('Arm and stop before moving.');const [axis,sign]=jogs[key],i=axis==='v'?0:1,max=i===0?cfg.vSpeed:cfg.hSpeed;let command;
  if(manualMode==='speed'){const speed=B.numeric(val('manualValue'),'Speed',0.001,1000),scale=stepsPerMm(),pulses=Math.round(speed*(manualUnit==='mm'?scale:1));if(pulses<cfg.start||pulses>max)throw Error('Speed must be '+(manualUnit==='mm'?(cfg.start/scale).toFixed(2)+'–'+(max/scale).toFixed(2)+' mm/s':cfg.start+'–'+max+' steps/s')+'.');command=`jog:${axis}:${sign}:${pulses}`;}
  else {const distance=B.numeric(val('manualValue'),'Distance',0.001,100000),steps=Math.round(distance*(manualUnit==='mm'?stepsPerMm():1));if(steps<1||steps>cfg.maxTravel)throw Error('Distance must be 1–'+cfg.maxTravel+' steps per hold.');command=`jogstep:${axis}:${sign}:${steps}`;}
  const id=++commandId;gate.begin(id,i,null);jogKey=key;motionGesture='jog';gestureReady=false;send(`${id}|${command}`);renderLive();}
function renderLive(){
  const f=fresh();$('connection').textContent=f?(simulation?'Simulator connected':'ESP connected'):(compatible?'Telemetry stale / disconnected':'Connecting / compatible firmware required');$('simulation').hidden=!simulation;
  $('machineState').textContent=!f?'OFFLINE':status.fault!=='none'?'FAULT':!status.enabled?'DISABLED':status.axis<0?'IDLE':'MOVING';
  $('faultDetail').textContent=!f?'No recent status from ESP. Check the USB cable, COM port, and Start UI window. Close Arduino Serial Monitor while using the UI.':status.fault==='USB/browser watchdog/disconnect'?'USB/browser connection watchdog tripped. After the link is stable, use Settings → Apply settings / clear fault, then Arm and home again.':status.fault!=='none'?'Fault: '+status.fault+'. Open Settings → Driver telemetry; apply settings while disabled after correcting the cause.':!status.ready?'Controller is not ready. Open Settings → Driver telemetry to see which driver check failed.':'';
  const scale=stepsPerMm();for(const [i,a]of ['y','x'].entries()){$(a+'Position').textContent=f?(status.position[i]/scale).toFixed(3):'—';$(a+'Home').textContent=f&&status.zeroed[i]?'Home established · counted position':'Home not established';}
  $('resolution').textContent=f?(1/scale).toFixed(6).replace(/0+$/,'').replace(/\.$/,''):'—';
  $('speed').textContent=f?(status.speed/scale).toFixed(2)+' mm/s':'—';$('remaining').textContent=f?(status.homing===1?'Seeking home':(status.remaining/scale).toFixed(3)+' mm'):'—';
  $('arm').disabled=!f||status.enabled||!status.ready||status.fault!=='none';
  $('driverSummary').innerHTML=f?status.drivers.map(d=>`<div class="driver"><span>${esc(d.name)}</span><span class="${d.selected&&d.seen&&d.configured&&d.age<1500?'ok':'bad'}">${!d.selected?'SKIPPED':d.age>=1500?'STALE':!d.seen?'UART MISSING':!d.configured?'CONFIG FAIL':'READY'}</span></div>`).join(''):'No live telemetry';
  const m=prepared?.[phaseIndex];$('phase').textContent=jogKey?'Manual move':m?m.phase:'No prepared move';$('gesture').textContent=jogKey?'Keep holding Shift + '+jogKey.slice(3)+'. Release stops.':m?(gate.pending?'Keep holding; release stops.':!gestureReady?'Release all motion keys first.':'Hold Shift + '+({down:'D',up:'U',forward:'F',back:'B'}[m.gesture])+'.'):'Use Manual Mode or prepare a bend.';
  for(const [id,key]of [['keyU','KeyU'],['keyD','KeyD'],['keyF','KeyF'],['keyB','KeyB']])$(id).classList.toggle('held',held.has(key));$('keyShift').classList.toggle('held',held.has('ShiftLeft')||held.has('ShiftRight'));
  if($('manualYPosition'))$('manualYPosition').textContent=f?(status.position[0]/scale).toFixed(3)+' mm':'— mm';if($('manualXPosition'))$('manualXPosition').textContent=f?(status.position[1]/scale).toFixed(3)+' mm':'— mm';
  $('modeSummary').textContent=`Y ${cfg.vLimitHoming?'switch':'manual'} home · X ${cfg.hLimitHoming?'switch':'manual'} home · ${cfg.microsteps}×`;
  if($('limitStatus'))$('limitStatus').textContent=f?`${cfg.vLimitHoming?'Y1 / Y2: '+status.limits[0]+' / '+status.limits[1]+' (0 closed, 1 open/tripped)':'Y switches disabled'} · ${cfg.hLimitHoming?'X: '+status.limits[2]+' (0 closed, 1 open/tripped)':'X switch disabled'}`:'No live switch inputs.';
  if($('diagnostics'))$('diagnostics').textContent=f?JSON.stringify(status.drivers.map(d=>({...d,diag:cfg.stopDiag?d.diag:'not used',edges:cfg.stopDiag?d.edges:'not used'})),null,2):'No live telemetry';
  if($('phaseStrip'))for(const el of $('phaseStrip').children)el.classList.toggle('current',Boolean(m&&m.phase.toLowerCase().includes(el.textContent.toLowerCase())));
}
function connect(){socket=new WebSocket('ws://'+location.host+'/ws');socket.onmessage=e=>{try{const s=JSON.parse(e.data);if(s.type==='hello'){client=s.id;compatible=s.protocol===3&&[25,50,100,200,400,800,1600,3200,6400].includes(s.stepsPerMm);simulation=s.simulation===true;setStorageMode(simulation);if(!compatible){say('Upload the checkpoint protocol 3 firmware; old firmware is not compatible.',true);return;}cfg=s.settings;say('Connected. Inspect settings, Arm, then establish homes.');render();}else if(s.type==='status'){status=s;lastRx=Date.now();cfg=s.settings||cfg;if(gate.pending){if(status.owner!==client)throw Error('Control ownership changed.');if(gate.status(s))complete();}if(prepared&&(!mine()||status.fault!=='none'))cancel('Prepared sequence canceled: controller not ready.');renderLive();}else if(s.type==='result'){gate.result(s);}else if(s.notice)say(s.notice);}catch(err){cancel();say(err.message,true);}};socket.onclose=()=>{gate.cancel();prepared=null;jogKey=null;held.clear();status=null;client=-1;compatible=false;renderLive();say('Disconnected. Reconnect requires explicit Arm and home.',true);setTimeout(connect,1500);};socket.onerror=()=>{};}
const motionKeys=new Set(['ShiftLeft','ShiftRight','KeyU','KeyD','KeyF','KeyB']);
function editing(target){return target?.matches('input,textarea,select,[contenteditable=true]');}
addEventListener('keydown',e=>{if(e.code==='Escape'||(e.code==='Space'&&!editing(e.target))){e.preventDefault();cancel();return;}if(!motionKeys.has(e.code)||editing(e.target)||document.hidden)return;e.preventDefault();if(e.repeat)return;held.add(e.code);attempt(()=>{executePrepared();startJog();});renderLive();});
addEventListener('keyup',e=>{held.delete(e.code);if(jogKey&&!jogHeld(jogKey))cancel('Key released; motion stopped.');else if(gate.pending&&motionGesture!=='jog'&&!gestureDown(motionGesture))cancel('Key released; sequence stopped. Prepare again to continue.');if(held.size===0)gestureReady=true;renderLive();});
addEventListener('blur',()=>cancel('Window lost focus; control released.',true));addEventListener('pagehide',()=>cancel('',true));document.addEventListener('visibilitychange',()=>{if(document.hidden)cancel('',true);});
document.addEventListener('focusin',e=>{if(editing(e.target)&&(gate.pending||prepared))cancel('Editing canceled the prepared move.');});
bind('arm',()=>{if(!compatible)throw Error('Compatible firmware required.');send('arm');});bind('stop',()=>cancel());bind('disable',()=>{cancel('Drivers disabled; establish homes again before absolute motion.');send('disable');});
setInterval(()=>{const armed=compatible&&socket?.readyState===1&&status?.owner===client&&status.enabled&&status.fault==='none'&&!document.hidden;if(armed)send('beat');if(gate.pending){if(!mine())cancel('Motion stopped: telemetry stale or controller unavailable.',true);else if(motionGesture==='jog'?jogHeld(jogKey):gestureDown(motionGesture))send('hold:'+gate.pending.id);else cancel('Input hold lost.');}else if(prepared&&!mine())cancel('Prepared move canceled: telemetry stale or controller unavailable.');renderLive();},80);
render();if(storageError)say(storageError,true);connect();




