'use strict';
const $=id=>document.getElementById(id), B=Brake;
let KEY='press-brake-library-v1', profileKey='press-brake-settings-v1';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let db=B.defaults(), storageError='';
try{const saved=localStorage.getItem(KEY);if(saved)db=B.validateLibrary(JSON.parse(saved));}catch(e){storageError='Saved library could not load: '+e.message;}
let page='Run', socket, client=-1, status=null, cfg={...B.settings}, lastRx=0, compatible=false, simulation=false;
let selected=db.bends[0]?.id||null, editId=null, prepared=null, phaseIndex=0, cycle=false, gestureReady=false, pointerHeld=false;
let commandId=Date.now()%1000000000, gate=new B.MoveGate(), held=new Set(), motionGesture=null, eventLog=[];
const names=['Run','Create Bend','Punch/Die & Materials','Back Gauge','Manual Mode','Settings'];
function say(message,error=false){$('notice').textContent=message;$('notice').classList.toggle('error',error);eventLog.unshift(new Date().toLocaleTimeString()+' '+message);eventLog=eventLog.slice(0,40);}
function save(){B.validateLibrary(db);try{localStorage.setItem(KEY,JSON.stringify(db));}catch{throw Error('Browser storage could not save. Export a backup before closing.');}}
function send(command){if(socket?.readyState!==1)throw Error('Controller disconnected.');socket.send(command);}
function fresh(){return compatible&&status&&socket?.readyState===1&&Date.now()-lastRx<600;}
function mine(){return fresh()&&status.enabled&&status.fault==='none'&&status.owner===client;}
function idle(){return mine()&&status.axis===-1&&!gate.pending;}
function attempt(fn){try{fn();}catch(e){say(e.message,true);}}
function cancel(message='Stopped. Prepare a move to continue.',disable=false){gate.cancel();prepared=null;cycle=false;phaseIndex=0;gestureReady=false;motionGesture=null;pointerHeld=false;held.clear();if(socket?.readyState===1){socket.send('stop');if(disable&&status?.owner===client)socket.send('disable');}if(message)say(message);renderLive();}
function field(id,label,value,type='number',options=''){return `<label class="field">${esc(label)}<input id="${id}" type="${type}" value="${esc(value)}" ${type==='number'?'step="any"':''} ${options}></label>`;}
function check(id,label,value=false){return `<label class="check"><input type="checkbox" id="${id}" ${value?'checked':''}>${esc(label)}</label>`;}
function val(id){return $(id).value;}function num(id){return B.numeric(val(id),$(id).parentElement.textContent.trim(),0,1e6);}
function intro(title,text,tag=''){return `<div class="intro"><div><h1>${title}</h1><p class="muted">${text}</p></div>${tag?`<span class="tag">${tag}</span>`:''}</div>`;}
function button(id,text,cls=''){return `<button id="${id}" class="${cls}">${text}</button>`;}
function bind(id,fn){$(id)?.addEventListener('click',()=>attempt(fn));}
function setStorageMode(isSimulation){
  const key='press-brake-library-v1'+(isSimulation?'-simulation':'');
  profileKey='press-brake-settings-v1'+(isSimulation?'-simulation':'');
  if(KEY===key)return;
  KEY=key;db=B.defaults();
  try{const saved=localStorage.getItem(KEY);if(saved)db=B.validateLibrary(JSON.parse(saved));}catch(e){say('Library could not load: '+e.message,true);}
  selected=db.bends[0]?.id||null;editId=null;
}
function currentBend(){return db.bends.find(b=>b.id===selected);}
function render(){
  $('tabs').innerHTML=names.map(n=>`<button class="${n===page?'active':''}" data-page="${esc(n)}">${esc(n)}</button>`).join('');
  for(const btn of $('tabs').children)btn.onclick=()=>{cancel('',false);page=btn.dataset.page;render();};
  ({'Run':runPage,'Create Bend':bendPage,'Punch/Die & Materials':toolsPage,'Back Gauge':gaugePage,'Manual Mode':manualPage,'Settings':settingsPage})[page]();renderLive();
}
function runPage(){
  const b=currentBend();
  $('page').innerHTML=intro('Run a bend','One calibrated bend, one deliberate phase at a time.','SINGLE BEND')+`<div class="card"><h2>Saved bends</h2>${db.bends.length?db.bends.map(x=>`<div class="saved-row ${selected===x.id?'selected':''}"><div><strong>${esc(x.name)}</strong><small>${esc(x.angle)}° included · ${esc(x.width)} mm width · ${esc(db.material.thickness)} mm material</small></div><button data-select="${esc(x.id)}">Select</button></div>`).join(''):'<p class="muted">Start in Punch/Die & Materials, then create your first bend.</p>'}<div class="actions">${button('newBend','+ Create bend')}${button('editBend','Edit selected','subtle')}${button('duplicateBend','Duplicate','subtle')}</div></div><div class="card"><h2>${esc(b?.name||'No bend selected')}</h2><div class="phase-strip" id="phaseStrip">${['Gauge','Approach','Clamp','Bend','Retract'].map(x=>`<span>${x}</span>`).join('')}</div><div class="grid">${['approach','clamp','final','retract'].map(k=>`<div class="muted">${k.toUpperCase()}<div class="big-coordinate">${b?esc(b[k]):'—'} <small>mm</small></div></div>`).join('')}</div><p class="muted">Manual-depth calibration. Angle and width describe your recipe; they do not automatically calculate penetration. Clamp completion is a position, not measured grip.</p><div class="actions">${button('prepareBend','Prepare single bend','primary')}${button('cancelRun','Cancel','subtle')}</div></div>`;
  for(const btn of document.querySelectorAll('[data-select]'))btn.onclick=()=>{cancel('');selected=btn.dataset.select;render();};
  bind('newBend',()=>{editId=null;page='Create Bend';render();});
  bind('editBend',()=>{if(!b)throw Error('Select a bend.');editId=b.id;page='Create Bend';render();});
  bind('duplicateBend',()=>{if(!b)throw Error('Select a bend.');const copy={...b,id:String(Date.now()),name:b.name+' copy',calibrated:false};db.bends.push(copy);save();selected=editId=copy.id;page='Create Bend';render();});
  bind('prepareBend',()=>{if(!idle())throw Error('Connect, Arm and stop before preparing.');const moves=B.plan(b,db,cfg,status);prepare(moves,true);});bind('cancelRun',()=>cancel());
}
function bendPage(){
  const b=db.bends.find(x=>x.id===editId)||{name:'Aluminum flashing bend',width:20,angle:90,approach:0,clamp:0,final:0,retract:0,x:0,useX:false,calibrated:false,notes:''};
  $('page').innerHTML=intro('Create bend','Save a repeatable recipe using depths you have physically checked.','MANUAL DEPTH')+`<div class="card"><div class="grid">${field('bendName','Bend name',b.name,'text')}${field('bendAngle','Desired included angle (°)',b.angle)}${field('bendWidth','Bend width along tooling (mm)',b.width)}<div><label class="field">Installed setup</label><p>${esc(db.tools.punch.name)} / ${esc(db.tools.die.name)}<br><small>${esc(db.material.name)} · ${esc(db.material.thickness)} mm</small></p></div></div><div class="banner">Y is positive downward from your home. Enter taught coordinates; no automatic angle-to-depth calculation is used.</div><div class="grid" style="margin-top:20px">${['approach','clamp','final','retract'].map(k=>`<div>${field('bend_'+k,k[0].toUpperCase()+k.slice(1)+' Y (mm)',b[k])}<button data-teach="${k}" class="subtle">Use current Y</button></div>`).join('')}</div>${check('bendUseX','Position backgauge before approach',b.useX)}${field('bendX','Backgauge X from retracted home, toward die (mm)',b.x)}${check('bendCalibrated','I checked these depths for this tooling, thickness and desired angle.',b.calibrated)}<label class="field">Calibration / setup notes<textarea id="bendNotes">${esc(b.notes)}</textarea></label><div class="actions">${button('saveBend','Save bend & load into Run','primary')}${button('removeBend','Delete bend','danger')}</div></div>`;
  for(const btn of document.querySelectorAll('[data-teach]'))btn.onclick=()=>attempt(()=>{if(!idle()||!status.zeroed[0])throw Error('Home Y and stop before teaching.');$('bend_'+btn.dataset.teach).value=(status.position[0]/200).toFixed(3);$('bendCalibrated').checked=false;});
  for(const id of ['bendAngle','bendWidth','bend_approach','bend_clamp','bend_final','bend_retract'])$(id).addEventListener('input',()=>{$('bendCalibrated').checked=false;});
  bind('saveBend',()=>{cancel('');const name=val('bendName').trim();if(!name)throw Error('Enter a name.');const record={id:editId||String(Date.now()),name,angle:num('bendAngle'),width:num('bendWidth'),useX:$('bendUseX').checked,x:num('bendX'),calibrated:$('bendCalibrated').checked,notes:val('bendNotes'),setup:B.signature(db)};for(const k of ['approach','clamp','final','retract'])record[k]=num('bend_'+k);if(record.angle<1||record.angle>179)throw Error('Included angle must be 1–179°.');const i=db.bends.findIndex(x=>x.id===record.id);if(i<0)db.bends.push(record);else db.bends[i]=record;save();selected=record.id;page='Run';render();say('Bend saved. Prepare validates depths, homes, tooling and travel before any motion.');});
  bind('removeBend',()=>{if(!editId)return;db.bends=db.bends.filter(x=>x.id!==editId);save();editId=null;selected=db.bends[0]?.id;page='Run';render();});
}
function toolsPage(){
  $('page').innerHTML=intro('Punch / Die & Materials','Record the tooling actually installed on this machine.')+`<div class="grid three"><div class="card"><h2>Punch</h2>${field('p_name','Name',db.tools.punch.name,'text')}${field('p_part','Part number',db.tools.punch.part,'text')}${field('p_length','Usable length along bend (mm)',db.tools.punch.length)}${field('p_height','Height / depth (mm)',db.tools.punch.height)}${field('p_width','Body width (mm)',db.tools.punch.width)}${field('p_tipRadius','Tip radius (mm)',db.tools.punch.tipRadius)}${field('p_angle','Included tool angle / minimum bend angle (°)',db.tools.punch.angle)}</div><div class="card"><h2>Die</h2>${field('d_name','Name',db.tools.die.name,'text')}${field('d_part','Part number',db.tools.die.part,'text')}${field('d_length','Usable length along bend (mm)',db.tools.die.length)}${field('d_height','Height / depth (mm)',db.tools.die.height)}${field('d_width','Body width (mm)',db.tools.die.width)}${field('d_opening','V opening (mm)',db.tools.die.opening)}${field('d_angle','Included tool angle / minimum bend angle (°)',db.tools.die.angle)}</div><div class="card"><h2>Material</h2>${field('m_name','Name',db.material.name,'text')}${field('m_thickness','Thickness (mm)',db.material.thickness)}${field('m_springback','Springback notes value (°, not applied)',db.material.springback)}<p class="muted">Default: 0.2 mm aluminum flashing. Use a test coupon to establish the depth for your desired angle.</p></div></div><div class="card" style="margin-top:16px"><h2>Installed setup travel limit</h2>${field('toolDepth','Deepest permitted Y from home (mm)',db.tools.maxDepth)}<p class="muted">Choose a measured clearance limit above punch/die collision. Geometry entries do not calculate this for you. This limit applies to manual and program moves after homing. A value of 0 prevents downward travel from home. Maximum machine Y: ${(cfg.vMax/200).toFixed(3)} mm.</p><div class="actions">${button('saveTools','Save setup','primary')}${button('applyToolLimit','Apply saved depth limit to controller')}</div><p class="muted">Applying requires disabled outputs, then Arm and home again. Tooling/material edits require reviewing and resaving affected bends.</p></div>`;
  bind('saveTools',()=>{cancel('');const copy=JSON.parse(JSON.stringify(db));for(const [prefix,obj]of [['p',copy.tools.punch],['d',copy.tools.die]])for(const k of Object.keys(obj))obj[k]=['name','part'].includes(k)?val(prefix+'_'+k).trim():num(prefix+'_'+k);copy.material.name=val('m_name');copy.material.thickness=num('m_thickness');copy.material.springback=num('m_springback');copy.tools.maxDepth=num('toolDepth');B.validateLibrary(copy);db=copy;save();say('Tooling and material saved locally. Apply the saved depth limit before running.');});
  bind('applyToolLimit',()=>apply({...cfg,toolMax:B.pulses(db.tools.maxDepth)}));
}
function homeCard(axis){const label=axis==='v'?'Y · Punch':'X · Backgauge';return `<div class="card"><h2>${label} home</h2><p class="muted">${cfg.limitHoming?'Switch homing: seek negative, square Y within the configured budget, then back off. Hold A + L.':'Jog to the chosen reference, stop, then declare that physical location home. Y home is the retracted punch; X home is the retracted gauge.'}</p><div class="actions">${button('zero_'+axis,'Set current spot as home')}${button('home_'+axis,'Prepare switch home')}${button('return_'+axis,'Prepare return to home')}</div></div>`;}
function bindHomes(axis){bind('zero_'+axis,()=>{if(!idle())throw Error('Arm and stop before setting home.');if(cfg.limitHoming)throw Error('Disable switch homing in Settings to set a manual home.');cancel('');send('zero:'+axis);});bind('home_'+axis,()=>{if(!cfg.limitHoming)throw Error('Switch homing is off. Use manual home, or enable installed switches in Settings.');if(!idle())throw Error('Arm and stop first.');prepare([{phase:'Switch home '+axis.toUpperCase(),axis,target:null,op:'home',gesture:'pair'}]);});bind('return_'+axis,()=>manualTarget(axis,0,'Return to home'));}
function manualControls(axis){return `<div class="card"><h2>${axis==='v'?'Punch positioning':'Backgauge positioning'}</h2><div class="grid">${field('increment','Jog increment (mm; maximum 1 mm before home)',0.1)}${field('target','Absolute target from home (mm)',0)}</div><div class="pair-buttons">${button('negative',axis==='v'?'↑ Prepare UP increment':'← Prepare AWAY increment')}${button('positive',axis==='v'?'↓ Prepare DOWN increment':'→ Prepare TOWARD DIE increment')}</div><div class="actions">${button('moveTarget','Prepare target')}${button('holdMove','Hold to execute prepared manual move','primary')}</div><p class="muted">After preparing, use the indicated keyboard gesture. The hold button is available for upward punch moves and backgauge moves; downward punch moves require A + L. Release stops; each increment requires a fresh hold. Check physical direction with 0.1 mm before setting home.</p></div>`;}
function bindManual(axis){for(const [id,sign] of [['negative',-1],['positive',1]])bind(id,()=>{if(!idle())throw Error('Arm and stop first.');const amount=B.pulses(num('increment'))*sign;if(!amount)throw Error('Increment is below one pulse.');const i=axis==='v'?0:1;if(!status.zeroed[i]){if(Math.abs(amount)>200)throw Error('Before home, use at most 1 mm per increment.');prepare([{phase:'Setup increment (unhomed)',axis,target:status.position[i]+amount,amount,op:'step',gesture:axis==='v'&&sign<0?'up':'pair'}]);}else manualTarget(axis,(status.position[i]+amount)/200,'Manual increment');});bind('moveTarget',()=>manualTarget(axis,num('target'),'Move to target'));const btn=$('holdMove');btn.onpointerdown=e=>attempt(()=>{if(e.button!==0)return;e.preventDefault();btn.setPointerCapture(e.pointerId);pointerHeld=true;executePrepared(true);});for(const name of ['pointerup','pointercancel','lostpointercapture'])btn.addEventListener(name,()=>{pointerHeld=false;if(gate.pending)cancel('Hold released; move stopped.');else gestureReady=true;});}
function manualMove(axis,mm,label){if(!idle())throw Error('Arm and stop first.');const i=axis==='v'?0:1;if(!status.zeroed[i])throw Error('Set this axis home first.');const target=B.pulses(mm),max=i===0?Math.min(cfg.vMax,cfg.toolMax):cfg.hMax;if(target<0||target>max)throw Error('Target is outside the machine/tool envelope.');if(Math.abs(target-status.position[i])>cfg.maxTravel)throw Error('Move exceeds the command budget.');return {phase:label,axis,target,gesture:i===0&&target<status.position[i]?'up':'pair'};}
function manualTarget(axis,mm,label){prepare([manualMove(axis,mm,label)]);}
function gaugePage(){$('page').innerHTML=intro('Back gauge','X only · both horizontal motors share STEP.','POSITIVE = TOWARD DIE')+homeCard('h')+manualControls('h')+'<p class="muted">No motorized R axis. Current X is measured in commanded steps from the retracted reference, not flange length.</p>';bindHomes('h');bindManual('h');}
function manualPage(){$('page').innerHTML=intro('Manual mode','Teach positions and check motion in small, deliberate increments.','POSITIVE Y = DOWN')+homeCard('v')+manualControls('v')+`<div class="card"><h2>Manual stroke</h2><div class="grid">${field('strokeStart','Start / clearance Y (mm)',0)}${field('strokeEnd','End Y (mm)',0)}</div>${button('prepareStroke','Prepare start → end → retract')}<p class="muted">Hold A + L for approach, Shift + ↓ for the stroke, then Shift + ↑ to retract. Repeating cycles is not enabled in this checkpoint.</p></div>`;bindHomes('v');bindManual('v');bind('prepareStroke',()=>{const start=num('strokeStart'),end=num('strokeEnd');manualMove('v',end,'Stroke validation');manualMove('v',start,'Stroke validation');if(end<=start)throw Error('End must be below start.');if(B.pulses(end-start)>cfg.maxTravel)throw Error('Stroke exceeds command budget.');prepare([{phase:'Stroke approach',axis:'v',target:B.pulses(start),gesture:'pair'},{phase:'Manual stroke',axis:'v',target:B.pulses(end),gesture:'down'},{phase:'Stroke retract',axis:'v',target:B.pulses(start),gesture:'up'}],true);});}
function settingsPage(){
  $('page').innerHTML=intro('Settings','Controller configuration is applied while disabled; homes must then be re-established.')+`<div class="card"><h2>Homing & optional sensing</h2>${check('limitHoming','Use installed mechanical limit switches for homing',cfg.limitHoming)}<p class="muted">Off: set manual homes. On: GPIO34/35 home Y independently; GPIO36 homes X. NC wiring with external pull-ups; open/tripped reads 1. Confirm direction and input states before using switch homing.</p>${check('stopDiag','Stop on DIAG / StallGuard (only when wired and tested)',cfg.stopDiag)}<p class="muted">Off is correct while DIAG wires are absent. UART driver protection remains active. No load or force measurement is inferred.</p><p id="limitStatus" class="banner"></p></div><details class="card" open><summary>Advanced · Motion configuration & diagnostics</summary><p class="muted">200 STEP pulses = 1 mm. Speed values here are pulses/second. Travel envelope: Y 0–25 mm maximum, X 0–48 mm maximum. Reduce to the measured usable range.</p><div class="grid">${B.fields.map(([k,label,unit,min,max])=>field('cfg_'+k,label+(unit?' ('+unit+')':''),cfg[k],'number',`min="${min}" max="${max}"`)).join('')}</div><div class="actions">${button('applySettings','Apply settings / clear fault','primary')}${button('exportApplied','Print applied settings to Serial')}</div><p class="muted">Settings are RAM-only on the ESP. A copy is stored in this browser after a successful apply; restoring it never arms or homes automatically.</p>${button('restoreProfile','Load saved settings into form','subtle')}<details><summary>Driver telemetry</summary><pre id="diagnostics"></pre></details><details><summary>Recent notices</summary><pre id="events">${esc(eventLog.join('\n'))}</pre></details></details><div class="card"><h2>Library backup</h2><div class="actions">${button('exportLibrary','Export tooling & bends')}<label class="field">Import library<input id="importLibrary" type="file" accept="application/json,.json"></label></div><p class="muted">Import replaces this browser's library. Keep an exported backup. Saved jobs and controller settings are separate.</p></div><div class="card"><h2>Connection</h2><p class="muted">UI stays on this computer. WebSocket commands pass through the local Node server. On boot: preferred Wi-Fi → iPhone (8) → saved custom network → PressBrake-Setup. The setup portal disables motion. Restart the launcher with the new ESP address after changing networks.</p><p class="muted">Cloud hosting and sign-in are a later phase; this checkpoint does not expose the machine publicly.</p>${simulation?button('sample','Load simulation example','subtle'):''}</div>`;
  bind('applySettings',()=>{const next={};for(const [k]of B.fields)next[k]=num('cfg_'+k);next.stopDiag=$('stopDiag').checked;next.limitHoming=$('limitHoming').checked;apply(next);});
  bind('restoreProfile',()=>{const p=JSON.parse(localStorage.getItem(profileKey)||'null');B.validateSettings(p);for(const [k]of B.fields)$('cfg_'+k).value=p[k];$('stopDiag').checked=p.stopDiag;$('limitHoming').checked=p.limitHoming;say('Profile loaded into form only. Inspect it, then Apply while disabled.');});
  bind('exportApplied',()=>send('export'));bind('exportLibrary',()=>{const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='press-brake-library.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
  $('importLibrary').onchange=async e=>{try{cancel('');const f=e.target.files[0];if(!f)return;if(f.size>100000)throw Error('Library is too large.');db=B.validateLibrary(JSON.parse(await f.text()));save();selected=db.bends[0]?.id;render();say('Library imported. Review tooling and apply the controller limit before running.');}catch(err){say(err.message,true);}};
  bind('sample',()=>{if(!simulation)throw Error('Simulation only.');db=B.defaults();Object.assign(db.tools.punch,{name:'DEMO punch',length:100,height:20,width:10});Object.assign(db.tools.die,{name:'DEMO V die',length:100,height:10,width:20,opening:8});db.tools.maxDepth=10;db.bends=[{id:'demo',name:'DEMO · 0.2 mm flashing',width:25,angle:90,approach:2,clamp:3,final:3.3,retract:2,x:5,useX:true,calibrated:true,notes:'Simulation example only. Never reuse these positions on hardware.',setup:B.signature(db)}];selected='demo';say('Simulation example loaded in memory only. Apply 10 mm tool limit, Arm, and set both homes.');page='Run';render();});
}
async function apply(next){try{if(!fresh()||status.enabled)throw Error('Connect and Disable drivers before applying.');B.validateSettings(next);const data=new URLSearchParams;for(const [k,v]of Object.entries(next))data.set(k,typeof v==='boolean'?(v?'1':'0'):String(v));const res=await fetch('/settings',{method:'POST',body:data});const text=await res.text();if(!res.ok)throw Error(text);cfg={...next};try{localStorage.setItem(profileKey,JSON.stringify(cfg));}catch{}say(text);render();}catch(e){say(e.message,true);}}
function prepare(moves,isCycle=false){if(!idle())throw Error('Arm and stop first.');gate.cancel();prepared=JSON.parse(JSON.stringify(moves));phaseIndex=0;cycle=isCycle;gestureReady=held.size===0&&!pointerHeld;motionGesture=null;say('Prepared. '+(gestureReady?'Hold the indicated controls to start.':'Release all keys, then hold the indicated controls.'));renderLive();}
function gestureDown(kind){return kind==='pair'?held.has('KeyA')&&held.has('KeyL'):held.has('ShiftLeft')||held.has('ShiftRight')?held.has(kind==='down'?'ArrowDown':'ArrowUp'):false;}
function executePrepared(pointer=false){if(!prepared||gate.pending||!gestureReady)return;if(!idle())throw Error('Motion is not available.');const m=prepared[phaseIndex];if(pointer&&(cycle||m.op==='home'||(m.axis==='v'&&m.target>status.position[0])))throw Error('Use the indicated keyboard gesture for downward punch motion, homing, and stroke sequences.');if(!pointer&&!gestureDown(m.gesture))return;const id=++commandId;gate.begin(id,m.axis==='v'?0:1,m.target);gestureReady=false;motionGesture=pointer?'pointer':m.gesture;const command=m.op==='home'?'home:'+m.axis:m.op==='step'?`step:${m.axis}:${m.amount}`:`goto:${m.axis}:${m.target}`;send(id+'|'+command);renderLive();}
function complete(){motionGesture=null;phaseIndex++;if(phaseIndex>=prepared.length){prepared=null;cycle=false;say('Complete. Motion stopped; motors remain armed.');}else say('Phase complete. Release controls, then hold for '+prepared[phaseIndex].phase+'.');gestureReady=false;renderLive();}
function renderLive(){
  const f=fresh();$('connection').textContent=f?(simulation?'Simulator connected':'ESP connected'):(compatible?'Telemetry stale / disconnected':'Connecting / compatible firmware required');$('simulation').hidden=!simulation;
  $('machineState').textContent=!f?'OFFLINE':status.fault!=='none'?'FAULT':!status.enabled?'DISABLED':status.axis<0?'IDLE':'MOVING';
  for(const [i,a]of ['y','x'].entries()){$(a+'Position').textContent=f?(status.position[i]/200).toFixed(3):'—';$(a+'Home').textContent=f&&status.zeroed[i]?'Home established · counted position':'Home not established';}
  $('speed').textContent=f?(status.speed/200).toFixed(2)+' mm/s':'—';$('remaining').textContent=f?(status.homing===1?'Seeking home':(status.remaining/200).toFixed(3)+' mm'):'—';
  $('arm').disabled=!f||status.enabled||!status.ready||status.fault!=='none';
  $('driverSummary').innerHTML=f?status.drivers.map(d=>`<div class="driver"><span>${esc(d.name)}</span><span class="${d.selected&&d.seen&&d.configured&&d.age<1500?'ok':'bad'}">${!d.selected?'SKIPPED':d.age>=1500?'STALE':d.seen&&d.configured?'READY':'CHECK'}</span></div>`).join(''):'No live telemetry';
  const m=prepared?.[phaseIndex];$('phase').textContent=m?m.phase:'No prepared move';$('gesture').textContent=m?(gate.pending?'Keep holding; release stops.':!gestureReady?'Release all motion keys first.':m.gesture==='pair'?'Hold A + L together.':m.gesture==='down'?'Hold Shift + ↓.':'Hold Shift + ↑.'):'Prepare a bend or manual move.';
  for(const [id,key]of [['keyA','KeyA'],['keyL','KeyL'],['keyDown','ArrowDown'],['keyUp','ArrowUp']])$(id).classList.toggle('held',held.has(key));$('keyShift').classList.toggle('held',held.has('ShiftLeft')||held.has('ShiftRight'));
  $('modeSummary').textContent=(cfg.limitHoming?'Switch home':'Manual home')+' · DIAG '+(cfg.stopDiag?'on':'off');
  if($('limitStatus'))$('limitStatus').textContent=f&&cfg.limitHoming?'Home inputs Y1 / Y2 / X: '+status.limits.join(' / ')+' (0 closed, 1 open/tripped)':'Switch inputs not used while manual homing is selected.';
  if($('diagnostics'))$('diagnostics').textContent=f?JSON.stringify(status.drivers.map(d=>({...d,diag:cfg.stopDiag?d.diag:'not used',edges:cfg.stopDiag?d.edges:'not used'})),null,2):'No live telemetry';
  if($('phaseStrip'))for(const el of $('phaseStrip').children)el.classList.toggle('current',Boolean(m&&m.phase.toLowerCase().includes(el.textContent.toLowerCase())));
}
function connect(){socket=new WebSocket('ws://'+location.host+'/ws');socket.onmessage=e=>{try{const s=JSON.parse(e.data);if(s.type==='hello'){client=s.id;compatible=s.protocol===2&&s.stepsPerMm===200;simulation=s.simulation===true;setStorageMode(simulation);if(!compatible){say('Upload the checkpoint protocol 2 firmware; old firmware is not compatible.',true);return;}cfg=s.settings;say('Connected. Inspect settings, Arm, then establish homes.');render();}else if(s.type==='status'){status=s;lastRx=Date.now();cfg=s.settings||cfg;if(gate.pending){if(status.owner!==client)throw Error('Control ownership changed.');if(gate.status(s))complete();}if(prepared&&(!mine()||status.fault!=='none'))cancel('Prepared sequence canceled: controller not ready.');renderLive();}else if(s.type==='result'){gate.result(s);}else if(s.notice)say(s.notice);}catch(err){cancel();say(err.message,true);}};socket.onclose=()=>{gate.cancel();prepared=null;held.clear();status=null;client=-1;compatible=false;renderLive();say('Disconnected. Reconnect requires explicit Arm and home.',true);setTimeout(connect,1500);};socket.onerror=()=>{};}
const motionKeys=new Set(['KeyA','KeyL','ShiftLeft','ShiftRight','ArrowDown','ArrowUp']);
function editing(target){return target?.matches('input,textarea,select,[contenteditable=true]');}
addEventListener('keydown',e=>{if(e.code==='Escape'||(e.code==='Space'&&!editing(e.target))){e.preventDefault();cancel();return;}if(!motionKeys.has(e.code)||editing(e.target)||document.hidden)return;e.preventDefault();if(e.repeat)return;held.add(e.code);attempt(()=>executePrepared());renderLive();});
addEventListener('keyup',e=>{held.delete(e.code);if(gate.pending&&motionGesture!=='pointer'&&!gestureDown(motionGesture)){cancel('Key released; sequence stopped. Prepare again to continue.');}if(held.size===0&&!pointerHeld)gestureReady=true;renderLive();});
addEventListener('blur',()=>cancel('Window lost focus; control released.',true));addEventListener('pagehide',()=>cancel('',true));document.addEventListener('visibilitychange',()=>{if(document.hidden)cancel('',true);});
document.addEventListener('focusin',e=>{if(editing(e.target)&&(gate.pending||prepared))cancel('Editing canceled the prepared move.');});
bind('arm',()=>{if(!compatible)throw Error('Compatible firmware required.');send('arm');});bind('stop',()=>cancel());bind('disable',()=>{cancel('Drivers disabled; establish homes again before absolute motion.');send('disable');});
setInterval(()=>{if(mine()&&!document.hidden){send('beat');if(gate.pending){if(motionGesture==='pointer'?pointerHeld:gestureDown(motionGesture))send('hold:'+gate.pending.id);else cancel('Input hold lost.');}}else if(gate.pending||prepared)cancel('Telemetry stale or controller unavailable.',true);renderLive();},80);
render();if(storageError)say(storageError,true);connect();




