(function(root,factory){const api=factory();if(typeof module==='object')module.exports=api;else root.Brake=api;})(globalThis,()=>{
  'use strict';
  const defaults=()=>({version:2,machine:{punchToTable:74},tools:{punches:[{id:'p1',name:'My punch',height:0}],dies:[{id:'d1',name:'My die',height:0,opening:0}],selectedPunchId:'p1',selectedDieId:'d1',maxDepth:0},material:{name:'Cold Rolled Steel',tensile:45000,radiusPercent:15,springback:0.7},bends:[],nextId:1});
  const settings={microsteps:4,current:600,hold:50,precharge:400,vSpeed:500,vAccel:200,hSpeed:500,hAccel:200,start:20,maxTravel:10000,sgthrs:0,senseMin:100,settle:300,toolMax:0,homeSpeed:200,homeBackoff:200,stopDiag:false,vLimitHoming:true,hLimitHoming:false};
  const fields=[['microsteps','Microstepping','×',1,256],['current','Run current / motor','mA RMS',300,1000],['hold','Hold current','%',30,100],['precharge','Current precharge','ms',100,2000],['vSpeed','Y maximum speed','steps/s',20,10000],['vAccel','Y acceleration','steps/s²',10,40000],['hSpeed','X maximum speed','steps/s',20,10000],['hAccel','X acceleration','steps/s²',10,40000],['start','Start / final speed','steps/s',5,2000],['maxTravel','Maximum move budget','steps',1,1000000],['toolMax','Installed tool maximum Y','steps',0,160000],['homeSpeed','Switch homing speed','steps/s',20,10000],['homeBackoff','Switch backoff','steps',20,12800],['sgthrs','StallGuard threshold','',0,255],['senseMin','DIAG minimum speed','steps/s',1,10000],['settle','DIAG settling time','ms',100,2000]];
  const pulseFields=['vSpeed','vAccel','hSpeed','hAccel','start','maxTravel','toolMax','homeSpeed','homeBackoff','senseMin'];
  function numeric(value,name,min=0,max=1e6){if(value===''||value===null||typeof value==='boolean')throw Error(name+' is required.');const n=Number(value);if(!Number.isFinite(n)||n<min||n>max)throw Error(name+' must be between '+min+' and '+max+'.');return n;}
  function stepsPerMm(c=settings){return 25*c.microsteps;}
  function pulses(mm,c=settings){return Math.round(numeric(mm,'Position',-1000,1000)*stepsPerMm(c));}
  function validateSettings(c){for(const [k,label,,lo,hi]of fields){numeric(c[k],label,lo,hi);if(!Number.isInteger(c[k]))throw Error(label+' must be a whole number.');}if(![1,2,4,8,16,32,64,128,256].includes(c.microsteps))throw Error('Microstepping must be a power of two from 1 to 256.');if(c.start>Math.min(c.vSpeed,c.hSpeed))throw Error('Start speed exceeds a stage speed.');if(c.homeBackoff>c.maxTravel)throw Error('Home backoff exceeds the move budget.');for(const k of ['stopDiag','vLimitHoming','hLimitHoming'])if(typeof c[k]!=='boolean')throw Error('Invalid '+k);return c;}
  function migrate(raw){if(raw?.version!==1)return raw;const d=defaults(),p=raw.tools?.punch||d.tools.punches[0],die=raw.tools?.die||d.tools.dies[0];return {...raw,version:2,machine:{punchToTable:74},tools:{punches:[{id:'p1',...p}],dies:[{id:'d1',...die}],selectedPunchId:'p1',selectedDieId:'d1',maxDepth:raw.tools?.maxDepth||0},bends:(raw.bends||[]).map(b=>({...b,punchId:'p1',dieId:'d1',manualPositions:false,setup:''}))};}
  function tool(db,type,id){const list=type==='punch'?db.tools.punches:db.tools.dies;return list.find(x=>x.id===(id||(type==='punch'?db.tools.selectedPunchId:db.tools.selectedDieId)));}
  function validateLibrary(input){const db=migrate(input);if(db?.version!==2||!db.machine||!db.tools||!Array.isArray(db.tools.punches)||!Array.isArray(db.tools.dies)||!db.material||!Array.isArray(db.bends)||db.bends.length>100)throw Error('Unsupported library file.');if(!db.tools.punches.length||!db.tools.dies.length||db.tools.punches.length>100||db.tools.dies.length>100)throw Error('At least one punch and die are required.');const ids=new Set();for(const [kind,list]of [['punch',db.tools.punches],['die',db.tools.dies]])for(const t of list){if(typeof t.id!=='string'||!t.id||ids.has(t.id)||typeof t.name!=='string'||!t.name.trim()||t.name.length>160)throw Error('Invalid '+kind+'.');ids.add(t.id);numeric(t.height,'Tool height',0,2000);if(kind==='die')numeric(t.opening,'V opening',0,1000);}if(!tool(db,'punch')||!tool(db,'die'))throw Error('Selected punch or die is missing.');numeric(db.machine.punchToTable,'Punch-to-table distance',1,2000);numeric(db.tools.maxDepth,'Tool depth limit',0,1000);if(typeof db.material.name!=='string'||db.material.name.length>160)throw Error('Invalid material name.');numeric(db.material.tensile??45000,'Material tensile strength',0,1000000);numeric(db.material.radiusPercent??15,'Inside bend radius percentage',0,1000);numeric(db.material.springback,'Material springback',0,90);for(const b of db.bends){if(typeof b.id!=='string'||typeof b.name!=='string'||b.name.length>160)throw Error('Invalid bend.');numeric(b.width,'Width',0,2000);numeric(b.angle,'Angle',0,180);numeric(b.x??0,'Backgauge',-2000,2000);numeric(b.final,'Bottom position',-2000,2000);if(typeof b.useX!=='boolean')throw Error('Invalid gauge selection.');b.manualPositions=Boolean(b.manualPositions);if(b.manualPositions){numeric(b.offset,'Manual offset position',-2000,2000);numeric(b.clamp,'Manual clamp position',-2000,2000);}if(!tool(db,'punch',b.punchId)||!tool(db,'die',b.dieId))throw Error('A bend references missing tooling.');}return db;}
  function geometry(db,punchId,dieId,bend){const p=tool(db,'punch',punchId),d=tool(db,'die',dieId);if(!p||!d)throw Error('Select a saved punch and die.');const contact=-(numeric(db.machine.punchToTable,'Punch-to-table distance',1,2000)-numeric(p.height,'Punch height',0,2000)-numeric(d.height,'Die height',0,2000));return {start:-5,contact,offset:bend?.manualPositions?Number(bend.offset):contact+6,clamp:bend?.manualPositions?Number(bend.clamp):contact+0.2,punch:p,die:d,manual:Boolean(bend?.manualPositions)};}
  function signature(db,punchId,dieId){return JSON.stringify([tool(db,'punch',punchId),tool(db,'die',dieId),db.material,db.machine]);}
  function overrideError(warnings){const e=Error(warnings.join(' '));e.overrideable=true;e.warnings=warnings;return e;}
  function plan(b,db,c,status,{override=false}={}){
    validateLibrary(db);validateSettings(c);if(!b)throw Error('Select a saved bend.');
    if(b.setup!==signature(db,b.punchId,b.dieId))throw Error('Tooling, material, or machine geometry changed. Review and save this bend again.');
    if(!b.calibrated)throw Error('Confirm the bottom position for this tooling and material.');
    if(!status?.zeroed?.[0]||(b.useX&&!status.zeroed[1]))throw Error('Set required Y/X homes first.');
    numeric(b.width,'Bend width',0.1,2000);numeric(b.angle,'Included angle',1,179);
    const g=geometry(db,b.punchId,b.dieId,b),warnings=[];
    if(!(g.offset<g.start&&g.clamp<g.offset&&b.final<g.clamp))warnings.push((g.manual?'Manual':'Calculated')+' offset, clamp, and bottom positions are outside the expected bend order.');
    const cap=db.tools.maxDepth?pulses(db.tools.maxDepth,c):0;
    if(cap&&c.toolMax!==cap)warnings.push('The saved tooling depth limit is not applied at the current step scale.');
    const moves=[{phase:'Move to offset position',instruction:g.manual?'Move the punch to the saved manual offset position.':'Move the punch to 6 mm above calculated tool contact.',axis:'v',target:pulses(g.offset,c),gesture:'down'}];
    if(b.useX)moves.push({phase:'Position backgauge',instruction:'Move the backgauge to the saved bend position.',axis:'h',target:pulses(b.x,c),gesture:'pair'});
    moves.push({phase:'Move to clamp position',instruction:g.manual?'Move the punch to the saved manual clamp position.':'Lower the punch to 0.2 mm above calculated tool contact.',axis:'v',target:pulses(g.clamp,c),gesture:'pair'},{phase:'Form bend',instruction:'Move to the programmed bottom position.',axis:'v',target:pulses(b.final,c),gesture:'pair',autoContinue:true},{phase:'Return to clamp',instruction:'The punch returns to clamp while A + L remains held.',axis:'v',target:pulses(g.clamp,c),gesture:'pair'},{phase:'Return to start',instruction:'Raise the punch to the 5 mm starting position.',axis:'v',target:pulses(g.start,c),gesture:'up'});
    const pos=[...status.position];for(const m of moves){const i=m.axis==='v'?0:1;if(Math.abs(m.target-pos[i])>c.maxTravel)warnings.push(m.phase+' exceeds the configured per-command move budget.');if(i===0&&cap&&m.target<-cap)warnings.push(m.phase+' exceeds the installed tooling depth limit.');pos[i]=m.target;}
    const unique=[...new Set(warnings)];if(unique.length&&!override)throw overrideError(unique);if(override&&unique.length)for(const m of moves)m.force=true;return moves;
  }
  class MoveGate{constructor(){this.pending=null;}begin(id,axis,target,now=Date.now()){if(this.pending)throw Error('A move is already pending.');this.pending={id,axis,target,accepted:false,at:now};}result(r){if(!this.pending||r.id!==this.pending.id)return;if(!r.ok){this.pending=null;throw Error(r.message||'Move rejected.');}this.pending.accepted=true;}status(s,now=Date.now()){const p=this.pending;if(!p)return false;if(s.fault!=='none'||!s.enabled){this.pending=null;throw Error(s.fault!=='none'?s.fault:'Outputs disabled.');}if(!p.accepted&&now-p.at>1500){this.pending=null;throw Error('No acknowledgement; stopped.');}if(p.accepted&&s.completedId===p.id&&s.axis===-1){if(p.target!==null&&s.position[p.axis]!==p.target){this.pending=null;throw Error('Completion position mismatch.');}this.pending=null;return true;}if(p.accepted&&s.axis===-1&&s.moveId!==p.id&&now-p.at>1000){this.pending=null;throw Error('Move stopped before completion.');}return false;}cancel(){this.pending=null;}}
  return {defaults,settings,fields,pulseFields,numeric,pulses,validateSettings,validateLibrary,signature,geometry,tool,plan,MoveGate,stepsPerMm};
});
