// Test event handlers in a minimal DOM double; no browser or hardware automation.
const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),B=require('./ui/model.js');
function harness(){const elements=new Map(),events={},timers=[];class Element{constructor(){this.children=[];this.value='0';this.checked=false;this.events={};this.classList={toggle(){}};this.parentElement={textContent:'Field'};}addEventListener(k,fn){this.events[k]=fn;}matches(){return false;}querySelectorAll(){return [];}setPointerCapture(){}}
  const document={hidden:false,getElementById(id){if(!elements.has(id))elements.set(id,new Element());return elements.get(id);},querySelectorAll(){return [];},addEventListener(k,fn){events[k]=fn;}};
  const messages=[],store=new Map();let ws;class Socket{constructor(){this.readyState=1;ws=this;}send(s){messages.push(s);}}
  const context=vm.createContext({Brake:B,document,WebSocket:Socket,localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},location:{host:'test'},setInterval:fn=>timers.push(fn),setTimeout(){},addEventListener:(k,fn)=>events[k]=fn,console,URLSearchParams,Date});
  vm.runInContext(fs.readFileSync('ui/app.js','utf8'),context);
  const receive=s=>ws.onmessage({data:JSON.stringify(s)});
  const status={type:'status',protocol:4,stepsPerMm:100,enabled:true,ready:true,fault:'none',owner:1,position:[0,0],zeroed:[true,true],axis:-1,speed:0,remaining:0,moveId:0,completedId:0,limits:[0,0,0],settings:{...B.settings,toolMax:2000},drivers:[]};
  receive({type:'hello',protocol:4,stepsPerMm:100,id:1,settings:status.settings});receive(status);
  return {run:s=>vm.runInContext(s,context),receive,status,messages,events,tick:()=>timers.forEach(fn=>fn()),key:(code,up=false,editing=false,repeat=false)=>events[up?'keyup':'keydown']({code,repeat,target:{matches:()=>editing},preventDefault(){}})};
}
test('Shift and direction required; repeat does not resend; releasing either stops',()=>{const h=harness();h.run("prepare([{phase:'Approach',axis:'v',target:-100,gesture:'down'}])");h.key('KeyD');assert.equal(h.messages.length,0);h.key('ShiftLeft');assert.match(h.messages.at(-1),/\|goto:v:-100$/);const n=h.messages.length;h.key('KeyD',false,false,true);assert.equal(h.messages.length,n);h.key('ShiftLeft',true);assert.equal(h.messages.at(-1),'stop');assert.equal(h.run('gate.pending'),null);});
test('phase transition requires release and fresh Shift D gesture',()=>{const h=harness();h.run("prepare([{phase:'Approach',axis:'v',target:-100,gesture:'down'},{phase:'Clamp',axis:'v',target:-150,gesture:'down'}],true)");h.key('ShiftLeft');h.key('KeyD');const id=Number(h.messages.at(-1).split('|')[0]);h.receive({type:'result',id,ok:true});h.receive({...h.status,completedId:id,position:[-100,0]});const n=h.messages.length;h.key('KeyD',false,false,true);assert.equal(h.messages.length,n);h.key('KeyD',true);h.key('ShiftLeft',true);h.key('ShiftLeft');h.key('KeyD');assert.match(h.messages.at(-1),/\|goto:v:-150$/);});
test('typing motion letters in inputs does not move; blur sends disable',()=>{const h=harness();h.run("prepare([{phase:'Approach',axis:'v',target:-100,gesture:'down'}])");h.key('KeyD',false,true);assert.equal(h.messages.length,0);h.key('ShiftLeft');h.key('KeyD');h.events.blur();assert.deepEqual(h.messages.slice(-2),['stop','disable']);});
test('stale status cancels and prevents hold renewal',()=>{const h=harness();h.run("prepare([{phase:'Approach',axis:'v',target:-100,gesture:'down'}])");h.key('ShiftLeft');h.key('KeyD');h.run('lastRx=0');h.tick();assert.deepEqual(h.messages.slice(-2),['stop','disable']);assert.equal(h.run('prepared'),null);});
test('idle armed connection keeps heartbeat through a delayed status packet',()=>{const h=harness();h.run('lastRx=0');h.tick();assert.equal(h.messages.at(-1),'beat');assert.equal(h.messages.includes('disable'),false);});
test('manual held jog sends negative down at selected speed and stops on release',()=>{const h=harness();h.run("page='Manual Mode';render();$('manualValue').value='0.5'");h.key('ShiftLeft');h.key('KeyD');assert.match(h.messages.at(-1),/\|jog:v:-:50$/);h.key('ShiftLeft',true);assert.equal(h.messages.at(-1),'stop');assert.equal(h.run('gate.pending'),null);});
test('manual jog works before home and only on Manual Mode',()=>{const h=harness();h.key('ShiftLeft');h.key('KeyF');assert.equal(h.messages.length,0);h.key('KeyF',true);h.key('ShiftLeft',true);h.run("page='Manual Mode';render();$('manualValue').value='0.5'");h.receive({...h.status,zeroed:[true,false]});h.key('ShiftLeft');h.key('KeyF');assert.match(h.messages.at(-1),/\|jog:h:\+:50$/);});
test('distance mode sends bounded step count for either axis',()=>{const h=harness();h.run("page='Manual Mode';render();manualMode='distance';manualUnit='steps';$('manualValue').value='25'");h.key('ShiftLeft');h.key('KeyD');assert.match(h.messages.at(-1),/\|jogstep:v:-:25$/);});
test('Escape cancels even inside an editable field',()=>{const h=harness();h.run("prepare([{phase:'Approach',axis:'v',target:-100,gesture:'down'}])");h.key('Escape',false,true);assert.equal(h.messages.at(-1),'stop');assert.equal(h.run('prepared'),null);});
test('simulation storage does not overwrite hardware library',()=>{const h=harness();h.receive({type:'hello',protocol:4,stepsPerMm:100,id:1,simulation:true,settings:h.status.settings});assert.equal(h.run('KEY'),'press-brake-library-v1-simulation');assert.equal(h.run('profileKey'),'press-brake-settings-v1-simulation');});
test('A plus L advances the form and automatically starts the return to clamp',()=>{const h=harness();h.run("prepare([{phase:'Form bend',axis:'v',target:-100,gesture:'pair',autoContinue:true},{phase:'Return to clamp',axis:'v',target:-80,gesture:'pair'}],true)");h.key('KeyA');h.key('KeyL');const id=Number(h.messages.at(-1).split('|')[0]);h.receive({type:'result',id,ok:true});h.receive({...h.status,completedId:id,position:[-100,0]});assert.match(h.messages.at(-1),/\|goto:v:-80$/);});
test('prepared motion cannot execute without the matching keyboard gesture',()=>{const h=harness();h.run("prepare([{phase:'Downward move',axis:'v',target:-100,gesture:'down'}])");h.run('executePrepared()');assert.equal(h.messages.length,0);});
test('editing a field cancels an already prepared move',()=>{const h=harness();h.run("prepare([{phase:'Approach',axis:'v',target:-100,gesture:'down'}])");h.events.focusin({target:{matches:()=>true}});assert.equal(h.run('prepared'),null);});
